version: 2

sources:
  - name: QWT_RAW
    database: QWT_ANALYTICS
    schema: raw
    tables:
      - name: customers
      - name: products
      - name: orders
      - name: orderdetails

